version: '3.8'

services:
  web:
    build:
      context: .
    # reload enables auto reload so the server will restart after changes are made to the code base
    # workers 1 provides a single worker process
    # host 0.0.0.0 defines the address to host the server on
    # port 8000 defines the port to host the server on
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # The volume is used to mount the code into the container
    # This is a must for a development environment in order to update the container whenever a change to the source code is made
    # Without this, you would have to re-build the image each time you make a change to the code
    volumes:
      - ./:/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0