version: '3.8'

services:
  web:
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
    - 8004:8000
    volumes:
    - ./:/app
    environment:
    - ENVIRONMENT=dev
    - TESTING=0